# Generated by Django 5.2.1 on 2025-06-02 11:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_url",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="gallery/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "mp4",
                                    "avi",
                                    "mov",
                                    "mkv",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("image", "image"), ("video", "video")], max_length=10
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_items",
                        to="userprofile.profile",
                    ),
                ),
            ],
        ),
    ]
