# Generated by Django 5.2.1 on 2025-07-01 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usergallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryitem",
            name="item_url",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="media/usergallery/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "mp4",
                            "avi",
                            "mov",
                            "mkv",
                        ]
                    )
                ],
            ),
        ),
    ]
