# Generated by Django 5.2.1 on 2025-07-02 22:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental_ratings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="helpful_votes",
            field=models.IntegerField(
                default=0, help_text="Number of users who found this review helpful"
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="is_edited",
            field=models.BooleanField(
                default=False, help_text="Whether this rating has been edited"
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="is_verified_purchase",
            field=models.BooleanField(
                default=False,
                help_text="Whether this rating is from a verified purchase",
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="reported",
            field=models.BooleanField(
                default=False, help_text="Whether this rating has been reported"
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["item_id", "rating"], name="rental_rati_item_id_e08ffd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["user", "created_at"], name="rental_rati_user_id_071592_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["rating", "created_at"], name="rental_rati_rating_82e706_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["is_verified_purchase", "rating"],
                name="rental_rati_is_veri_dfc72b_idx",
            ),
        ),
    ]
