# Generated by Django 5.2 on 2025-07-06 14:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("userprofile", "0027_alter_headshot_professional_headshot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("talents", models.CharField(max_length=255)),
                ("project_type", models.CharField(max_length=100)),
                ("organization_type", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=255)),
                ("company_website", models.URLField(blank=True, null=True)),
                ("job_title", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=100)),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Postal code must be a 4-digit number (e.g., 1000 for Addis Ababa).",
                                regex="^\\d{4}$",
                            )
                        ],
                    ),
                ),
                ("project_title", models.CharField(blank=True, max_length=255)),
                ("project_start_date", models.DateField(blank=True, null=True)),
                ("project_end_date", models.DateField(blank=True, null=True)),
                ("compensation_type", models.TextField(blank=True)),
                ("compensation_amount", models.CharField(blank=True, max_length=100)),
                ("project_details", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userprofile.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opportunity_description", models.TextField()),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userprofile.profile",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.job"
                    ),
                ),
            ],
        ),
    ]
