# Generated by Django 5.2 on 2025-05-08 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("talents", models.CharField(max_length=255)),
                ("project_type", models.CharField(max_length=100)),
                ("organization_type", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("company_website", models.URLField(blank=True, null=True)),
                ("job_title", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("project_title", models.CharField(blank=True, max_length=255)),
                ("project_start_date", models.DateField(blank=True, null=True)),
                ("project_end_date", models.DateField(blank=True, null=True)),
                ("compensation_type", models.CharField(blank=True, max_length=50)),
                ("compensation_amount", models.CharField(blank=True, max_length=100)),
                ("project_details", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
