# Generated by Django 5.2 on 2025-04-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_company_name_alter_job_company_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='compensation_amount',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='compensation_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='project_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='project_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='project_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='project_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
