# Generated by Django 5.2 on 2025-05-24 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_alter_job_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="compensation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Salary", "Salary"),
                    ("Hourly", "Hourly"),
                    ("Fixed", "Fixed"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="postal_code",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Postal code must be a 4-digit number (e.g., 1000 for Addis Ababa).",
                        regex="^\\d{4}$",
                    )
                ],
            ),
        ),
    ]
