# Generated by Django 5.2 on 2025-07-03 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_alter_job_compensation_type_application"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["-created_at"]},
        ),
    ]
