# Generated by Django 5.2.1 on 2025-07-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_options'),
        ('userprofile', '0027_alter_headshot_professional_headshot_and_more'),
    ]

    operations = [
        # This migration is intentionally empty because the table already exists
    ]
