# Generated by Django 5.2 on 2025-07-06 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_job_options"),
        ("userprofile", "0027_alter_headshot_professional_headshot_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="user",
        ),
        migrations.RemoveField(
            model_name="job",
            name="user_id",
        ),
        migrations.AddField(
            model_name="application",
            name="profile_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="userprofile.profile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="profile_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="userprofile.profile",
            ),
            preserve_default=False,
        ),
    ]
