# Generated by Django 5.2 on 2025-05-08 12:44

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_job_compensation_amount_job_compensation_type_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="job",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="job",
            name="project_details",
        ),
        migrations.RemoveField(
            model_name="job",
            name="project_end_date",
        ),
        migrations.RemoveField(
            model_name="job",
            name="project_start_date",
        ),
        migrations.RemoveField(
            model_name="job",
            name="project_title",
        ),
        migrations.RemoveField(
            model_name="job",
            name="user_id",
        ),
        migrations.AddField(
            model_name="job",
            name="application_deadline",
            field=models.DateField(
                blank=True, help_text="Deadline for job applications", null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="applications_count",
            field=models.IntegerField(
                default=0, help_text="Number of applications received"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="benefits",
            field=models.TextField(
                blank=True, help_text="Job benefits and perks", null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="company_size",
            field=models.CharField(
                blank=True, help_text="Size of the company", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="compensation_currency",
            field=models.CharField(
                default="USD", help_text="Currency for compensation", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="description",
            field=models.TextField(
                blank=True, help_text="Detailed job description", null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="education_level",
            field=models.CharField(
                blank=True,
                help_text="Required education level",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="email",
            field=models.EmailField(
                blank=True, help_text="Contact email address", max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="employment_type",
            field=models.CharField(
                blank=True,
                help_text="Type of employment (e.g., Full-time, Part-time, Contract)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="experience_level",
            field=models.CharField(
                blank=True,
                help_text="Required experience level",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="industry",
            field=models.CharField(
                blank=True, help_text="Industry sector", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="Whether this job is featured"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="languages_required",
            field=models.JSONField(
                default=list, help_text="List of required languages"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="location",
            field=models.CharField(
                blank=True, help_text="Job location", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="phone",
            field=models.CharField(
                blank=True, help_text="Contact phone number", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="project_duration",
            field=models.CharField(
                blank=True,
                help_text="Expected duration of the project",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="remote_work",
            field=models.BooleanField(
                default=False, help_text="Whether the job can be done remotely"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="requirements",
            field=models.TextField(
                blank=True, help_text="Job requirements and qualifications", null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="responsibilities",
            field=models.TextField(
                blank=True, help_text="Job responsibilities", null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="skills_required",
            field=models.JSONField(default=list, help_text="List of required skills"),
        ),
        migrations.AddField(
            model_name="job",
            name="start_date",
            field=models.DateField(
                blank=True, help_text="Expected start date", null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                    ("expired", "Expired"),
                ],
                default="draft",
                help_text="Current status of the job posting",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Tags for job categorization",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="job",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="views_count",
            field=models.IntegerField(
                default=0, help_text="Number of times the job has been viewed"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="company_name",
            field=models.CharField(
                help_text="Name of the company offering the job", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="company_website",
            field=models.URLField(
                blank=True, help_text="Company's website URL", null=True
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="compensation_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Compensation amount",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="compensation_type",
            field=models.CharField(
                choices=[
                    ("hourly", "Hourly"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                    ("project", "Project-based"),
                ],
                default="monthly",
                help_text="Type of compensation",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="country",
            field=models.CharField(
                help_text="Country where the job is located", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="first_name",
            field=models.CharField(
                help_text="Contact person's first name", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_title",
            field=models.CharField(
                help_text="Title of the job position", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="last_name",
            field=models.CharField(
                help_text="Contact person's last name", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="organization_type",
            field=models.CharField(
                blank=True, help_text="Type of organization", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="project_type",
            field=models.CharField(
                blank=True,
                help_text="Type of project (if applicable)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="talents",
            field=models.JSONField(
                default=list, help_text="List of required talents or specializations"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["status", "created_at"], name="jobs_job_status_277b31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["company_name"], name="jobs_job_company_8d1ffe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["job_title"], name="jobs_job_job_tit_ca70ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["location"], name="jobs_job_locatio_8b2f8c_idx"),
        ),
    ]
