# Generated by Django 5.2 on 2025-07-05 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_application_profile_id"),
        ("userprofile", "0027_alter_headshot_professional_headshot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="profile_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="userprofile.profile"
            ),
        ),
    ]
