services:
  - type: web
    name: talentsearch-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn talentsearch.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DJANGO_SETTINGS_MODULE
        value: talentsearch.settings.prod
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: talentsearch-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: talentsearch-redis
          property: connectionString
  - type: redis
    name: talentsearch-redis
    plan: free

databases:
  - name: talentsearch-db
    databaseName: talentsearch
    user: talentsearch
    plan: free 