services:
  - type: web
    name: talentsearch-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn talentsearch.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DJANGO_SETTINGS_MODULE
        value: talentsearch.settings.prod
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: talentsearch-db
          property: connectionString
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: true
      - key: EMAIL_HOST_USER
        value: abelyitages10@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: ftti eokt edjb newg

databases:
  - name: talentsearch-db
    databaseName: talentsearch
    user: talentsearch
    plan: free
