# Generated by Django 5.2 on 2025-04-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a concise news title (max 255 characters).', max_length=255)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('content', models.TextField(help_text='Provide the full news content')),
                ('image', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Auto-set creation date')),
            ],
        ),
    ]
