# Generated by Django 5.2.1 on 2025-06-02 11:53

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("news", "0001_initial"),
        ("taggit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Add relevant tags for categorization.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="image_gallery",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select images for the gallery.",
                to="news.newsimage",
            ),
        ),
    ]
