# Generated by Django 5.2.1 on 2025-07-01 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsimage",
            name="image",
            field=models.ImageField(
                help_text="Upload an image for the news gallery.",
                upload_to="media/news_images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif", "webp"],
                        message="Only jpg, jpeg, png, gif, webp files are allowed.",
                    )
                ],
            ),
        ),
    ]
