# Generated by Django 5.2 on 2025-05-24 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_newsimage_remove_news_category_remove_news_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="content",
            field=models.TextField(
                help_text="Provide the full news content.",
                validators=[
                    django.core.validators.MinLengthValidator(
                        10, message="Content must be at least 10 characters long."
                    ),
                    django.core.validators.MaxLengthValidator(
                        50000, message="Content cannot exceed 50,000 characters."
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="newsimage",
            name="image",
            field=models.ImageField(
                help_text="Upload an image for the news gallery.",
                upload_to="news_images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif", "webp"],
                        message="Only jpg, jpeg, png, gif, webp files are allowed.",
                    )
                ],
            ),
        ),
    ]
