# Generated by Django 5.2.1 on 2025-06-02 11:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("feed_posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("likes_count", models.IntegerField(default=0)),
                ("dislikes_count", models.IntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="feed_comments.comment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        db_column="post_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="feed_posts.feedpost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "feed_comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommentLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_like", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        db_column="comment_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="feed_comments.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "feed_comment_likes",
            },
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["post", "created_at"], name="feed_commen_post_id_813529_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["parent", "created_at"], name="feed_commen_parent__28ba01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["user", "created_at"], name="feed_commen_user_id_21d904_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commentlike",
            index=models.Index(
                fields=["comment", "user"], name="feed_commen_comment_dfe4a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commentlike",
            index=models.Index(
                fields=["user", "created_at"], name="feed_commen_user_id_8aac26_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="commentlike",
            unique_together={("comment", "user")},
        ),
    ]
