# Generated by Django 5.2.1 on 2025-07-04 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed_comments", "0001_initial"),
        ("userprofile", "0027_alter_headshot_professional_headshot_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                db_column="profile_id",
                help_text="Profile who created the comment",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="userprofile.profile",
            ),
        ),
        migrations.AddField(
            model_name="commentlike",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                db_column="profile_id",
                help_text="Profile who liked/disliked the comment",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_likes",
                to="userprofile.profile",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                help_text="User who created the comment",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="commentlike",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                help_text="User who liked/disliked the comment",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
