# Generated by Django 5.2.1 on 2025-06-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0002_alter_user_email_alter_user_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="notification",
            name="data",
            field=models.JSONField(
                blank=True, help_text="Additional data for the notification", null=True
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("info", "Information"),
                    ("warning", "Warning"),
                    ("alert", "Alert"),
                    ("system", "System"),
                    ("security", "Security"),
                    ("account", "Account"),
                    ("message", "Message"),
                    ("job", "Job"),
                    ("news", "News"),
                    ("comment", "Comment"),
                    ("like", "Like"),
                    ("rating", "Rating"),
                    ("rental", "Rental"),
                    ("advert", "Advert"),
                    ("profile", "Profile"),
                    ("verification", "Verification"),
                    ("payment", "Payment"),
                    ("support", "Support"),
                ],
                default="info",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "read"], name="authapp_not_user_id_1fab3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "notification_type"],
                name="authapp_not_user_id_56a498_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["created_at"], name="authapp_not_created_a9fa7f_idx"
            ),
        ),
    ]
