# Generated by Django 5.2 on 2025-05-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0002_alter_user_options_user_last_password_change_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
