# Generated by Django 5.2 on 2025-05-24 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0003_alter_notification_link_alter_notification_message_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login_success", "Login Success"),
                            ("login_failed", "Login Failed"),
                            ("password_change", "Password Change"),
                            ("password_reset", "Password Reset"),
                            ("account_lockout", "Account Lockout"),
                            ("api_key_rotation", "API Key Rotation"),
                            ("session_expired", "Session Expired"),
                            ("security_alert", "Security Alert"),
                        ],
                        max_length=50,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "event_type"],
                        name="authapp_sec_user_id_17bf2c_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="authapp_sec_created_1e6dc8_idx"
                    ),
                    models.Index(
                        fields=["ip_address"], name="authapp_sec_ip_addr_1767e9_idx"
                    ),
                ],
            },
        ),
    ]
