# Generated by Django 5.2 on 2025-05-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0004_securitylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="backup_email",
            field=models.EmailField(
                blank=True,
                help_text="Backup email for account recovery",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="failed_login_attempts",
            field=models.IntegerField(
                default=0, help_text="Number of failed login attempts"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_locked",
            field=models.BooleanField(
                default=False,
                help_text="Whether the account is locked due to failed attempts",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_failed_login",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of last failed login attempt",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="lockout_until",
            field=models.DateTimeField(
                blank=True, help_text="When the account lockout expires", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number for account recovery",
                max_length=20,
                null=True,
            ),
        ),
    ]
