# Generated by Django 5.2 on 2025-05-25 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0006_passwordresettoken"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="securitylog",
            name="authapp_sec_user_id_17bf2c_idx",
        ),
        migrations.RemoveIndex(
            model_name="securitylog",
            name="authapp_sec_created_1e6dc8_idx",
        ),
        migrations.RemoveIndex(
            model_name="securitylog",
            name="authapp_sec_ip_addr_1767e9_idx",
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="securitylog",
            name="details",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="securitylog",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="securitylog",
            name="event_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="securitylog",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="securitylog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="securitylog",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(fields=["token"], name="authapp_pas_token_00d350_idx"),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["user", "created_at"], name="authapp_pas_user_id_d03d4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitylog",
            index=models.Index(
                fields=["user", "event_type", "created_at"],
                name="authapp_sec_user_id_1f4f98_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securitylog",
            index=models.Index(
                fields=["email", "created_at"], name="authapp_sec_email_63e9dc_idx"
            ),
        ),
    ]
