# Generated by Django 5.2 on 2025-05-25 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0007_remove_securitylog_authapp_sec_user_id_17bf2c_idx_and_more"),
    ]

    operations = []
