# Generated by Django 5.2 on 2025-05-27 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0008_handle_security_logs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securitylog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
