# Generated by Django 5.2.1 on 2025-06-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental_items", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalitem",
            name="category",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="rentalitem",
            name="type",
            field=models.CharField(max_length=255),
        ),
    ]
