# Generated by Django 5.2 on 2025-05-22 09:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental_items", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rentalitem",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="rentalitem",
            name="image_urls",
        ),
        migrations.AddField(
            model_name="rentalitem",
            name="additional_images",
            field=models.JSONField(
                default=list, help_text="List of additional image paths"
            ),
        ),
        migrations.AddField(
            model_name="rentalitem",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Main image for the rental item",
                null=True,
                upload_to="rental_items/main/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="rentalitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("professional", "Professional"),
                    ("consumer", "Consumer"),
                    ("vintage", "Vintage"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rentalitem",
            name="specs",
            field=models.JSONField(help_text="Technical specifications of the item"),
        ),
        migrations.AlterField(
            model_name="rentalitem",
            name="type",
            field=models.CharField(
                choices=[
                    ("camera", "Camera"),
                    ("lighting", "Lighting"),
                    ("audio", "Audio"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rentalitemrating",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="rentalitemrating",
            name="rating",
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.CreateModel(
            name="RentalItemImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Additional image for the rental item",
                        upload_to="rental_items/additional/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "gif"]
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rental_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="rental_items.rentalitem",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
