# Generated by Django 5.2.1 on 2025-06-22 19:57

import django.core.validators
import django.db.models.deletion
import rental_items.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental_items", "0002_alter_rentalitem_category_alter_rentalitem_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalitem",
            name="additional_images",
            field=models.JSONField(
                default=list, help_text="List of additional image paths"
            ),
        ),
        migrations.AddField(
            model_name="rentalitem",
            name="image",
            field=models.CharField(
                blank=True,
                help_text="Main image path for the rental item",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rentalitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="rentalitem",
            name="specs",
            field=models.JSONField(help_text="Technical specifications of the item"),
        ),
        migrations.AlterField(
            model_name="rentalitemrating",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="rentalitemrating",
            name="rating",
            field=models.IntegerField(
                help_text="Rating value from 1 to 5",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="rentalitemrating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rental_item_ratings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="RentalItemImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Additional image for the rental item",
                        upload_to=rental_items.models.rental_item_image_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "gif"]
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rental_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="rental_items.rentalitem",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
