# Generated by Django 5.2 on 2025-05-22 19:45

import django.core.validators
import django.db.models.deletion
import rental_items.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental_items", "0002_remove_rentalitem_image_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="rentalitemimage",
            name="image",
            field=models.ImageField(
                help_text="Additional image for the rental item",
                upload_to=rental_items.models.rental_item_image_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="rentalitemrating",
            name="rating",
            field=models.IntegerField(
                help_text="Rating value from 1 to 5",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="rentalitemrating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rental_item_ratings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
