# Generated by Django 5.2.1 on 2025-06-22 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental_items", "0003_remove_rentalitem_image_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rentalitem",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="rentalitem",
            name="image_urls",
        ),
        migrations.AlterField(
            model_name="rentalitem",
            name="image",
            field=models.CharField(
                blank=True,
                help_text="Main image path for the rental item",
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif"]
                    )
                ],
            ),
        ),
    ]
