# Generated by Django 5.2.1 on 2025-06-22 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rental_items", "0003_remove_rentalitem_image_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rentalitem",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="rentalitem",
            name="image_urls",
        ),
    ]
