# Generated by Django 5.2.1 on 2025-06-22 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental_items", "0004_remove_rentalitem_image_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalitem",
            name="image",
            field=models.ImageField(
                help_text="Main image for the rental item",
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif"]
                    )
                ],
            ),
        ),
    ]
