# Generated by Django 5.2.1 on 2025-06-22 20:15

from django.db import migrations


def check_and_add_columns(apps, schema_editor):
    """Check if columns exist and add them only if they don't"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check if additional_images column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'rental_items_rentalitem' 
            AND column_name = 'additional_images'
        """)
        if not cursor.fetchone():
            # Add the column if it doesn't exist
            cursor.execute("""
                ALTER TABLE rental_items_rentalitem 
                ADD COLUMN additional_images JSONB DEFAULT '[]'::jsonb
            """)
        
        # Check if image column exists and is the right type
        cursor.execute("""
            SELECT column_name, data_type 
            FROM information_schema.columns 
            WHERE table_name = 'rental_items_rentalitem' 
            AND column_name = 'image'
        """)
        result = cursor.fetchone()
        if not result:
            # Add the column if it doesn't exist
            cursor.execute("""
                ALTER TABLE rental_items_rentalitem 
                ADD COLUMN image VARCHAR(100) NULL
            """)
        elif result[1] != 'character varying':
            # Alter the column type if it's not the right type
            cursor.execute("""
                ALTER TABLE rental_items_rentalitem 
                ALTER COLUMN image TYPE VARCHAR(100)
            """)


def reverse_check_and_add_columns(apps, schema_editor):
    """Reverse operation - do nothing"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("rental_items", "0004_remove_rentalitem_image_url_and_more"),
    ]

    operations = [
        migrations.RunPython(check_and_add_columns, reverse_check_and_add_columns),
    ]
