# Generated by Django 5.2.1 on 2025-07-01 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental_items", "0005_alter_rentalitem_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalitemimage",
            name="image",
            field=models.ImageField(
                help_text="Additional image for the rental item",
                upload_to="media/rental_items/main/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif"]
                    )
                ],
            ),
        ),
    ]
