# Generated by Django 5.2 on 2025-04-30 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='ender',
            new_name='sender',
        ),
    ]
