# Generated by Django 5.2.1 on 2025-07-05 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0003_create_threads_for_existing_messages"),
        ("userprofile", "0027_alter_headshot_professional_headshot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="receiver",
            field=models.ForeignKey(
                help_text="Profile who should receive the message",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to="userprofile.profile",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                help_text="Profile who sent the message",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to="userprofile.profile",
            ),
        ),
        migrations.AlterField(
            model_name="messagethread",
            name="participants",
            field=models.ManyToManyField(
                help_text="Profiles participating in this conversation",
                related_name="threads",
                to="userprofile.profile",
            ),
        ),
    ]
