# Generated by Django 5.2.1 on 2025-07-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0004_alter_message_receiver_alter_message_sender_and_more"),
    ]

    operations = []
