# Generated by Django 5.2.1 on 2025-07-06 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0005_create_missing_profiles"),
    ]

    operations = []
