# Generated by Django 5.2.1 on 2025-06-11 14:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the post",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(help_text="Content of the post")),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        help_text="Type of media (image or video)",
                        max_length=10,
                    ),
                ),
                (
                    "media_url",
                    models.FileField(
                        help_text="Media file for the post (image or video)",
                        upload_to="feed_posts/media/",
                    ),
                ),
                (
                    "project_title",
                    models.CharField(help_text="Title of the project", max_length=200),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("Film", "Film"),
                            ("TV", "TV"),
                            ("Commercial", "Commercial"),
                            ("Theater", "Theater"),
                            ("Music", "Music"),
                            ("Other", "Other"),
                        ],
                        help_text="Type of project",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Location of the project", max_length=200
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the post was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the post was last updated",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created the post",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
