# Generated by Django 5.2.1 on 2025-07-05 21:49

import django.db.models.deletion
import feed_posts.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed_posts", "0001_initial"),
        ("userprofile", "0027_alter_headshot_professional_headshot_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedpost",
            options={},
        ),
        migrations.AlterModelOptions(
            name="userfollow",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="feedpost",
            name="message",
        ),
        migrations.AddField(
            model_name="feedpost",
            name="content",
            field=models.TextField(
                blank=True, help_text="Content of the post", null=True
            ),
        ),
        migrations.AddField(
            model_name="feedpost",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Location of the project",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="feedpost",
            name="media_type",
            field=models.CharField(
                choices=[("image", "Image"), ("video", "Video")],
                default="image",
                help_text="Type of media (image or video)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="feedpost",
            name="project_title",
            field=models.CharField(
                blank=True, help_text="Title of the project", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="feedpost",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the post",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="feedpost",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date and time when the post was created"
            ),
        ),
        migrations.AlterField(
            model_name="feedpost",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for the post",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="feedpost",
            name="media_url",
            field=models.FileField(
                blank=True,
                help_text="Media file for the post (image or video)",
                null=True,
                upload_to=feed_posts.models.feed_post_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="feedpost",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                help_text="Profile who created the post",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_posts",
                to="userprofile.profile",
            ),
        ),
        migrations.AlterField(
            model_name="feedpost",
            name="project_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Film", "Film"),
                    ("TV", "TV"),
                    ("Commercial", "Commercial"),
                    ("Theater", "Theater"),
                    ("Music", "Music"),
                    ("Other", "Other"),
                ],
                help_text="Type of project",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="feedpost",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Date and time when the post was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="userfollow",
            name="follower",
            field=models.ForeignKey(
                help_text="The profile who is following.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to="userprofile.profile",
            ),
        ),
        migrations.AlterField(
            model_name="userfollow",
            name="following",
            field=models.ForeignKey(
                help_text="The profile being followed.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to="userprofile.profile",
            ),
        ),
        migrations.AlterField(
            model_name="userfollow",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
