# Generated by Django 5.2 on 2025-05-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed_posts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedpost",
            name="media_urls",
        ),
        migrations.AlterField(
            model_name="feedpost",
            name="media_url",
            field=models.FileField(
                help_text="Media file for the post (image or video)",
                upload_to="feed_posts/media/",
            ),
        ),
    ]
