# Generated by Django 5.2.1 on 2025-06-30 14:33

import feed_posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed_posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedpost",
            name="media_url",
            field=models.FileField(
                help_text="Media file for the post (image or video)",
                upload_to=feed_posts.models.feed_post_upload_path,
            ),
        ),
    ]
