# Generated by Django 5.2.1 on 2025-07-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feed_posts", "0001_initial"),
    ]

    operations = []
