# Generated by Django 5.2.1 on 2025-07-05 18:30

import django.db.models.deletion
import feed_posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed_posts", "0002_fix_existing_schema"),
        ("userprofile", "0027_alter_headshot_professional_headshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedpost",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                help_text="Profile who created the post",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_posts",
                to="userprofile.profile",
            ),
        ),
        migrations.AlterField(
            model_name="feedpost",
            name="media_url",
            field=models.FileField(
                help_text="Media file for the post (image or video)",
                upload_to=feed_posts.models.feed_post_upload_path,
            ),
        ),
        migrations.CreateModel(
            name="UserFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "follower",
                    models.ForeignKey(
                        help_text="The profile who is following.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to="userprofile.profile",
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        help_text="The profile being followed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="userprofile.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("follower", "following")},
            },
        ),
    ]
