# Generated by Django 5.2.1 on 2025-07-01 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed_posts", "0003_userfollow"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedpost",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent post for replies (null for top-level posts)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="feed_posts.feedpost",
            ),
        ),
    ]
