# Generated by Django 5.2.1 on 2025-07-06 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feed_posts", "0003_feedpost_profile_alter_feedpost_media_url_userfollow"),
    ]

    operations = [
        # This migration does nothing, just marks the previous one as applied
    ]
