# Generated by Django 5.2.1 on 2025-07-04 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feed_posts", "0004_feedpost_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedpost",
            name="parent",
        ),
    ]
