# Generated by Django 5.2.1 on 2025-07-04 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed_posts", "0005_remove_feedpost_parent"),
        ("userprofile", "0027_alter_headshot_professional_headshot_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE feed_posts_feedpost 
            ADD COLUMN profile_id INTEGER REFERENCES userprofile_profile(id) NULL;
            """,
            reverse_sql="""
            ALTER TABLE feed_posts_feedpost 
            DROP COLUMN profile_id;
            """,
            state_operations=[
                migrations.AddField(
                    model_name="feedpost",
                    name="profile",
                    field=models.ForeignKey(
                        blank=True,
                        help_text="Profile who created the post",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_posts",
                        to="userprofile.profile",
                    ),
                ),
            ]
        ),
        migrations.AlterField(
            model_name="userfollow",
            name="follower",
            field=models.ForeignKey(
                help_text="The profile who is following.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to="userprofile.profile",
            ),
        ),
        migrations.AlterField(
            model_name="userfollow",
            name="following",
            field=models.ForeignKey(
                help_text="The profile being followed.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to="userprofile.profile",
            ),
        ),
    ]
