# Generated by Django 5.2.1 on 2025-07-05 17:26

from django.db import migrations, models
import django.db.models.deletion

def cleanup_orphaned_userfollows(apps, schema_editor):
    """
    Clean up orphaned UserFollow records before fixing constraints.
    """
    UserFollow = apps.get_model('feed_posts', 'UserFollow')
    User = apps.get_model('authapp', 'User')
    
    # Get all user IDs that exist
    existing_user_ids = set(User.objects.values_list('id', flat=True))
    
    # Remove UserFollow records where follower or following user doesn't exist
    orphaned_follows = UserFollow.objects.exclude(
        follower_id__in=existing_user_ids
    ) | UserFollow.objects.exclude(
        following_id__in=existing_user_ids
    )
    
    count = orphaned_follows.count()
    if count > 0:
        print(f"Removing {count} orphaned UserFollow records")
        orphaned_follows.delete()
    else:
        print("No orphaned UserFollow records found")

class Migration(migrations.Migration):

    dependencies = [
        ("feed_posts", "0007_cleanup_orphaned_userfollows"),
        ("authapp", "0001_initial"),
    ]

    operations = [
        # First clean up orphaned records
        migrations.RunPython(
            cleanup_orphaned_userfollows,
            reverse_code=migrations.RunPython.noop
        ),
        
        # Then ensure the foreign key constraints are correct
        migrations.AlterField(
            model_name="userfollow",
            name="follower",
            field=models.ForeignKey(
                help_text="The profile who is following.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to="userprofile.profile",
            ),
        ),
        migrations.AlterField(
            model_name="userfollow",
            name="following",
            field=models.ForeignKey(
                help_text="The profile being followed.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to="userprofile.profile",
            ),
        ),
    ]
