# Generated by Django 5.2.1 on 2025-07-05 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feed_posts", "0008_fix_userfollow_foreign_keys"),
    ]

    operations = []
