# Generated by Django 5.2.1 on 2025-07-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedpost",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Date and time when the post was last updated"
            ),
        ),
    ]
