# Generated by Django 5.2.1 on 2025-07-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_feedpost_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentlike",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="commentlike",
            name="is_like",
            field=models.BooleanField(default=True),
        ),
    ]
