# Generated by Django 5.2 on 2025-05-08 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Full name of the user", max_length=255),
                ),
                (
                    "birthdate",
                    models.DateField(
                        blank=True, help_text="User's date of birth", null=True
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="User's weight in kg",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="User's height in cm",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "languages",
                    models.JSONField(
                        default=list, help_text="List of languages spoken"
                    ),
                ),
                (
                    "profession",
                    models.CharField(help_text="User's profession", max_length=100),
                ),
                (
                    "skills",
                    models.JSONField(default=list, help_text="List of user's skills"),
                ),
                (
                    "interests",
                    models.JSONField(
                        default=list, help_text="List of user's interests"
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="User's biography", null=True
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                (
                    "cover_photo",
                    models.ImageField(blank=True, null=True, upload_to="cover_photos/"),
                ),
                (
                    "social_links",
                    models.JSONField(
                        default=dict, help_text="Dictionary of social media links"
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("timezone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "preferences",
                    models.JSONField(
                        default=dict, help_text="User preferences and settings"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
