# Generated by Django 5.2.1 on 2025-06-11 21:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="personalinfo",
            options={
                "verbose_name": "Personal Information",
                "verbose_name_plural": "Personal Information",
            },
        ),
        migrations.RemoveField(
            model_name="personalinfo",
            name="award_recognitions",
        ),
        migrations.RemoveField(
            model_name="personalinfo",
            name="company_culture_preference",
        ),
        migrations.RemoveField(
            model_name="personalinfo",
            name="ethnicity",
        ),
        migrations.RemoveField(
            model_name="personalinfo",
            name="other_social_media",
        ),
        migrations.RemoveField(
            model_name="personalinfo",
            name="personality_type",
        ),
        migrations.RemoveField(
            model_name="personalinfo",
            name="special_skills",
        ),
        migrations.RemoveField(
            model_name="personalinfo",
            name="tools_experience",
        ),
        migrations.RemoveField(
            model_name="personalinfo",
            name="volunteer_experience",
        ),
        migrations.RemoveField(
            model_name="personalinfo",
            name="work_preference",
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="custom_language",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="custom_social_media",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="id_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="id_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("passport", "Passport"),
                    ("national_id", "National ID"),
                    ("drivers_license", "Driver's License"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="nationality",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="custom_hobby",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="hobbies",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="language_proficiency",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("married", "Married"),
                    ("divorced", "Divorced"),
                    ("widowed", "Widowed"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="social_media",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
