# Generated by Django 5.2.1 on 2025-06-11 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0002_alter_personalinfo_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinfo",
            name="date_of_birth",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="first_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                default="male",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="hobbies",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="id_number",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="id_type",
            field=models.CharField(
                choices=[
                    ("passport", "Passport"),
                    ("national_id", "National ID"),
                    ("drivers_license", "Driver's License"),
                ],
                default="national_id",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="language_proficiency",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="last_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("single", "Single"),
                    ("married", "Married"),
                    ("divorced", "Divorced"),
                    ("widowed", "Widowed"),
                ],
                default="single",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="nationality",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="social_media",
            field=models.JSONField(default=dict),
        ),
    ]
