# Generated by Django 5.2 on 2025-05-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0002_verificationauditlog_verificationstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professionalqualifications",
            name="travel_willingness",
            field=models.BooleanField(
                default=False, help_text="Are you willing to travel?"
            ),
        ),
    ]
