# Generated by Django 5.2.1 on 2025-06-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0003_alter_personalinfo_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinfo",
            name="date_of_birth",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="id_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="id_type",
            field=models.CharField(
                choices=[
                    ("passport", "Passport"),
                    ("national_id", "National ID"),
                    ("drivers_license", "Driver's License"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("single", "Single"),
                    ("married", "Married"),
                    ("divorced", "Divorced"),
                    ("widowed", "Widowed"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="nationality",
            field=models.CharField(max_length=100),
        ),
    ]
