# Generated by Django 5.2 on 2025-05-30 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0003_alter_professionalqualifications_travel_willingness"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalinfo",
            name="custom_hobby",
            field=models.CharField(
                blank=True,
                help_text="Custom hobby (required)",
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Custom hobby can only contain letters and spaces.",
                        regex="^[a-zA-Z\\s]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="emergency_contact",
            field=models.CharField(
                blank=True,
                help_text="Emergency contact name (required)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="emergency_phone",
            field=models.CharField(
                blank=True,
                help_text="Emergency contact phone number starting with +251 followed by 9 digits (required)",
                max_length=17,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must start with +251 followed by exactly 9 digits.",
                        regex="^\\+251\\d{9}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="physicalattributes",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Height in centimeters (required)",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Height cannot be negative"
                    ),
                    django.core.validators.MaxValueValidator(
                        300, message="Height cannot exceed 300 cm"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="physicalattributes",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Weight in kilograms (required)",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Weight cannot be negative"
                    ),
                    django.core.validators.MaxValueValidator(
                        500, message="Weight cannot exceed 500 kg"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="birthdate",
            field=models.DateField(
                blank=True, help_text="Date of birth (required)", null=True
            ),
        ),
    ]
