# Generated by Django 5.2 on 2025-06-04 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0002_add_professional_choices"),
        ("userprofile", "0004_personalinfo_custom_hobby_and_more"),
    ]

    operations = []
