# Generated by Django 5.2 on 2025-05-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0004_personalinfo_custom_hobby_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='specific_area',
            field=models.CharField(default='', help_text='Specific area (required)', max_length=200),
            preserve_default=False,
        ),
    ]
