# Generated by Django 5.2 on 2025-05-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0005_auto_20250530_0812"),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalqualifications',
            name='travel_willingness',
            field=models.BooleanField(default=False, help_text='Are you willing to travel?'),
        ),
        migrations.RunSQL(
            # Set default value for existing records
            sql='UPDATE userprofile_professionalqualifications SET travel_willingness = false WHERE travel_willingness IS NULL;',
            # Reverse SQL (not needed but good practice to include)
            reverse_sql='',
        ),
    ]
