# Generated by Django 5.2 on 2025-06-04 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0005_merge_20250604_1949"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region_id", models.CharField(max_length=50, unique=True)),
                ("region_name", models.CharField(max_length=100)),
                ("cities", models.JSONField()),
            ],
            options={
                "verbose_name": "Location Data",
                "verbose_name_plural": "Location Data",
            },
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="residence_type",
        ),
        migrations.RemoveField(
            model_name="personalinfo",
            name="social_media_handles",
        ),
        migrations.RemoveField(
            model_name="personalinfo",
            name="social_media_links",
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="country",
            field=models.CharField(
                default="ET", help_text="Country (required)", max_length=2
            ),
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="specific_area",
            field=models.CharField(
                blank=True,
                help_text="Specific area (required)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="last_cleanup",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="media",
            name="natural_photo_1",
            field=models.ImageField(
                blank=True,
                help_text="First natural photo (required). Must be JPG/PNG format, minimum 800px width, maximum 2000px width.",
                null=True,
                upload_to="natural_photos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                    django.core.validators.MinValueValidator(
                        800, message="Image width must be at least 800 pixels"
                    ),
                    django.core.validators.MaxValueValidator(
                        2000, message="Image width must not exceed 2000 pixels"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="natural_photo_1_processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="media",
            name="natural_photo_2",
            field=models.ImageField(
                blank=True,
                help_text="Second natural photo (required). Must be JPG/PNG format, minimum 800px width, maximum 2000px width.",
                null=True,
                upload_to="natural_photos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                    django.core.validators.MinValueValidator(
                        800, message="Image width must be at least 800 pixels"
                    ),
                    django.core.validators.MaxValueValidator(
                        2000, message="Image width must not exceed 2000px width"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="natural_photo_2_processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="media",
            name="photo_processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="other_social_media",
            field=models.JSONField(
                default=list,
                help_text="List of other social media platforms not in the predefined list",
            ),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="social_media",
            field=models.JSONField(
                default=list,
                help_text="List of social media accounts with usernames and followers",
            ),
        ),
        migrations.AddField(
            model_name="professionalqualifications",
            name="actor_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("amateur", "Amateur"),
                    ("professional", "Professional"),
                    ("stage", "Stage"),
                    ("screen", "Screen"),
                ],
                help_text="Category of acting experience",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="professionalqualifications",
            name="certifications",
            field=models.JSONField(
                default=list, help_text="List of certifications (optional)"
            ),
        ),
        migrations.AddField(
            model_name="professionalqualifications",
            name="employment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unemployed", "Unemployed"),
                    ("employed", "Employed"),
                    ("freelancer", "Freelancer"),
                ],
                help_text="Employment status (required)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="professionalqualifications",
            name="experience_description",
            field=models.TextField(
                blank=True, help_text="Detailed description of experience (optional)"
            ),
        ),
        migrations.AddField(
            model_name="professionalqualifications",
            name="influencer_categories",
            field=models.JSONField(
                default=list, help_text="Selected influencer categories"
            ),
        ),
        migrations.AddField(
            model_name="professionalqualifications",
            name="main_skill",
            field=models.CharField(
                blank=True,
                help_text="Primary skill (required for stuntman)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="professionalqualifications",
            name="model_categories",
            field=models.JSONField(default=list, help_text="Selected model categories"),
        ),
        migrations.AddField(
            model_name="professionalqualifications",
            name="performer_categories",
            field=models.JSONField(
                default=list, help_text="Selected performer categories"
            ),
        ),
        migrations.AddField(
            model_name="professionalqualifications",
            name="previous_employers",
            field=models.JSONField(
                default=list, help_text="List of previous employers (optional)"
            ),
        ),
        migrations.AddField(
            model_name="professionalqualifications",
            name="professions",
            field=models.JSONField(
                default=list, help_text="Selected professions (minimum 1 required)"
            ),
        ),
        migrations.AddField(
            model_name="professionalqualifications",
            name="skill_description",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of skills (required for Stuntman)",
            ),
        ),
        migrations.AddField(
            model_name="professionalqualifications",
            name="skill_videos_url",
            field=models.JSONField(
                default=list, help_text="URLs of skill videos (optional)"
            ),
        ),
        migrations.AddField(
            model_name="professionalqualifications",
            name="training_workshops",
            field=models.JSONField(
                default=list, help_text="List of training and workshops (optional)"
            ),
        ),
        migrations.AddField(
            model_name="professionalqualifications",
            name="video_links",
            field=models.JSONField(
                default=list, help_text="Video links (required for Voice Over)"
            ),
        ),
        migrations.AddField(
            model_name="professionalqualifications",
            name="video_url",
            field=models.URLField(
                blank=True, help_text="URL to showcase video (required for Stuntman)"
            ),
        ),
        migrations.AddField(
            model_name="professionalqualifications",
            name="years_of_experience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0_1", "0-1"),
                    ("1_3", "1-3"),
                    ("3_5", "3-5"),
                    ("5_plus", "5+"),
                ],
                help_text="Years of experience (required)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="address",
            field=models.CharField(help_text="Address (required)", max_length=200),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="city",
            field=models.CharField(help_text="City (required)", max_length=100),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="emergency_phone",
            field=models.CharField(
                blank=True,
                help_text="Emergency contact phone number (required)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="housing_status",
            field=models.CharField(
                choices=[
                    ("own", "Own"),
                    ("rent", "Rent"),
                    ("live_with_family", "Live with Family"),
                    ("other", "Other"),
                ],
                help_text="Housing status (required)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="region",
            field=models.CharField(help_text="Region (required)", max_length=50),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="residence_duration",
            field=models.CharField(
                choices=[
                    ("less_than_1", "<1 year"),
                    ("1_to_3", "1-3 years"),
                    ("3_to_5", "3-5 years"),
                    ("5_to_10", "5-10 years"),
                    ("more_than_10", ">10 years"),
                ],
                help_text="Duration of residence (required)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="identityverification",
            name="id_back",
            field=models.ImageField(
                blank=True,
                help_text="Back photo of ID document",
                null=True,
                upload_to="id_backs/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="identityverification",
            name="id_front",
            field=models.ImageField(
                blank=True,
                help_text="Front photo of ID document",
                null=True,
                upload_to="id_fronts/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="identityverification",
            name="id_type",
            field=models.CharField(
                choices=[
                    ("kebele_id", "Kebele ID"),
                    ("national_id", "National ID"),
                    ("passport", "Passport"),
                    ("driving_license", "Driving License"),
                ],
                help_text="Type of identification document",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Professional headshot (required). Must be JPG/PNG format, minimum 800px width, maximum 2000px width.",
                null=True,
                upload_to="profile_photos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                    django.core.validators.MinValueValidator(
                        800, message="Image width must be at least 800 pixels"
                    ),
                    django.core.validators.MaxValueValidator(
                        2000, message="Image width must not exceed 2000 pixels"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="custom_hobby",
            field=models.CharField(
                blank=True,
                help_text="Custom hobby (required)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="physicalattributes",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Height in centimeters (required)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="physicalattributes",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Weight in kilograms (required)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="professionalchoices",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="availability",
            field=models.CharField(
                choices=[
                    ("part_time", "Part-Time"),
                    ("full_time", "Full-Time"),
                    ("contract", "Contract"),
                    ("freelance", "Freelance"),
                ],
                help_text="Availability (required)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="communication_style",
            field=models.CharField(help_text="Communication style", max_length=50),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="driving_skills",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="experience_level",
            field=models.CharField(
                choices=[
                    ("entry", "Entry"),
                    ("mid_level", "Mid-Level"),
                    ("senior", "Senior"),
                ],
                help_text="Experience level (required)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="industry_experience",
            field=models.TextField(
                blank=True, help_text="Description of industry experience (optional)"
            ),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="leadership_style",
            field=models.CharField(help_text="Leadership style", max_length=50),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="max_salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="min_salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="motivation",
            field=models.CharField(help_text="Motivation", max_length=50),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="overtime_availability",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="preferred_company_size",
            field=models.CharField(help_text="Preferred company size", max_length=50),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="preferred_industry",
            field=models.CharField(help_text="Preferred industry", max_length=50),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="preferred_work_location",
            field=models.CharField(
                choices=[
                    ("hybrid", "Hybrid"),
                    ("onsite", "Onsite"),
                    ("remote", "Remote"),
                ],
                help_text="Preferred work location (required)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="reference",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="role_title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="shift_preference",
            field=models.CharField(
                choices=[
                    ("day", "Day"),
                    ("night", "Night"),
                    ("rotational", "Rotational"),
                ],
                help_text="Shift preference (required)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="skills",
            field=models.JSONField(default=list, help_text="Selected skills"),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="travel_willingness",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="union_membership",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="willingness_to_relocate",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="work_authorization",
            field=models.CharField(
                choices=[
                    ("authorized", "Authorized"),
                    ("unauthorized", "Unauthorized"),
                ],
                max_length=50,
            ),
        ),
    ]
