# Generated by Django 5.2.1 on 2025-06-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0005_alter_personalinfo_custom_hobby_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinfo",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
