# Generated by Django 5.2 on 2025-05-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0006_auto_20250530_0819"),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='country',
            field=models.CharField(default='ET', help_text='Country (required)', max_length=2),
            preserve_default=False,
        ),
        migrations.RunSQL(
            # Set default value for existing records
            sql='UPDATE userprofile_contactinfo SET country = \'ET\' WHERE country IS NULL;',
            # Reverse SQL (not needed but good practice to include)
            reverse_sql='',
        ),
    ]
