# Generated by Django 5.2.1 on 2025-06-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0007_alter_identityverification_id_back_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Choices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("subcategory", models.CharField(max_length=50)),
                ("choices", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Choice",
                "verbose_name_plural": "Choices",
            },
        ),
        migrations.DeleteModel(
            name="ChoiceData",
        ),
        migrations.DeleteModel(
            name="ProfessionalChoices",
        ),
        migrations.AddIndex(
            model_name="choices",
            index=models.Index(
                fields=["category", "subcategory"],
                name="userprofile_categor_27c233_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="choices",
            unique_together={("category", "subcategory")},
        ),
    ]
