# Generated by Django 5.2 on 2025-06-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "userprofile",
            "0007_genderchoices_hobbychoices_maritalstatuschoices_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LanguageChoices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choices", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MedicalInfoChoices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medical_conditions", models.JSONField(default=list)),
                ("medicine_types", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PhysicalAttributeChoices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hair_colors", models.JSONField(default=list)),
                ("eye_colors", models.JSONField(default=list)),
                ("skin_tones", models.JSONField(default=list)),
                ("body_types", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
