# Generated by Django 5.2 on 2025-06-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0008_languagechoices_medicalinfochoices_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NationalityChoices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choices", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProfessionChoices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choices", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="profile",
            name="nationality",
            field=models.CharField(help_text="Nationality (required)", max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profession",
            field=models.CharField(max_length=50),
        ),
    ]
