# Generated by Django 5.2 on 2025-05-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0008_auto_20250530_0824"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region_id", models.CharField(max_length=50, unique=True)),
                ("region_name", models.CharField(max_length=100)),
                ("cities", models.JSONField()),
            ],
            options={
                "verbose_name": "Location Data",
                "verbose_name_plural": "Location Data",
            },
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="country",
            field=models.CharField(help_text="Country (required)", max_length=2),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="custom_hobby",
            field=models.CharField(
                blank=True,
                help_text="Custom hobby (required)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="physicalattributes",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Height in centimeters (required)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="physicalattributes",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Weight in kilograms (required)",
                max_digits=5,
                null=True,
            ),
        ),
    ]
