# Generated by Django 5.2.1 on 2025-06-14 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0009_remove_education_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workexperience",
            name="internship_experience",
        ),
        migrations.RemoveField(
            model_name="workexperience",
            name="previous_employers",
        ),
        migrations.RemoveField(
            model_name="workexperience",
            name="projects",
        ),
        migrations.RemoveField(
            model_name="workexperience",
            name="training",
        ),
    ]
