# Generated by Django 5.2 on 2025-06-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0009_nationalitychoices_professionchoices_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DurationChoices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choices", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmploymentStatusChoices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choices", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExperienceLevelChoices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choices", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="HousingStatusChoices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choices", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="IDTypeChoices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choices", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RegionChoices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choices", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShiftChoices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choices", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SkillsChoices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choices", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkLocationChoices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choices", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="YearsChoices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choices", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name="ProfessionChoices",
            new_name="ActorCategoryChoices",
        ),
        migrations.RenameModel(
            old_name="HobbyChoices",
            new_name="AvailabilityChoices",
        ),
        migrations.DeleteModel(
            name="LanguageChoices",
        ),
        migrations.DeleteModel(
            name="MedicalInfoChoices",
        ),
        migrations.DeleteModel(
            name="PhysicalAttributeChoices",
        ),
        migrations.RemoveField(
            model_name="professionalqualifications",
            name="certifications",
        ),
        migrations.RemoveField(
            model_name="professionalqualifications",
            name="experience_description",
        ),
        migrations.RemoveField(
            model_name="professionalqualifications",
            name="industry_experience",
        ),
        migrations.RemoveField(
            model_name="professionalqualifications",
            name="max_salary",
        ),
        migrations.RemoveField(
            model_name="professionalqualifications",
            name="min_salary",
        ),
        migrations.RemoveField(
            model_name="professionalqualifications",
            name="previous_employers",
        ),
        migrations.RemoveField(
            model_name="professionalqualifications",
            name="skill_videos_url",
        ),
        migrations.RemoveField(
            model_name="professionalqualifications",
            name="training_workshops",
        ),
        migrations.RemoveField(
            model_name="professionalqualifications",
            name="video_links",
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="housing_status",
            field=models.CharField(
                help_text="Housing status (required)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="residence_duration",
            field=models.CharField(
                help_text="Duration of residence (required)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="identityverification",
            name="id_type",
            field=models.CharField(
                help_text="Type of identification document", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="marital_status",
            field=models.CharField(
                help_text="Marital status (required)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="physicalattributes",
            name="gender",
            field=models.CharField(help_text="Gender (required)", max_length=20),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="actor_category",
            field=models.CharField(
                blank=True, help_text="Category of acting experience", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="availability",
            field=models.CharField(help_text="Availability (required)", max_length=50),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="employment_status",
            field=models.CharField(
                blank=True,
                help_text="Employment status (required)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="experience_level",
            field=models.CharField(
                help_text="Experience level (required)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="preferred_work_location",
            field=models.CharField(
                help_text="Preferred work location (required)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="shift_preference",
            field=models.CharField(
                help_text="Shift preference (required)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="work_authorization",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="years_of_experience",
            field=models.CharField(
                blank=True,
                help_text="Years of experience (required)",
                max_length=50,
                null=True,
            ),
        ),
    ]
