# Generated by Django 5.2 on 2025-05-30 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0009_locationdata_alter_contactinfo_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinfo",
            name="country",
            field=models.CharField(
                default="ET", help_text="Country (required)", max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="custom_hobby",
            field=models.CharField(
                blank=True,
                help_text="Custom hobby (required if not selecting from predefined hobbies)",
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Custom hobby can only contain letters and spaces.",
                        regex="^[a-zA-Z\\s]+$",
                    )
                ],
            ),
        ),
    ]
