# Generated by Django 5.2.1 on 2025-06-14 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0010_remove_work_experience_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professionalqualifications",
            name="driving_skills",
        ),
        migrations.RemoveField(
            model_name="professionalqualifications",
            name="software_proficiency",
        ),
        migrations.RemoveField(
            model_name="professionalqualifications",
            name="typing_speed",
        ),
    ]
