# Generated by Django 5.2 on 2025-06-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0010_durationchoices_employmentstatuschoices_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="professionalqualifications",
            name="max_salary",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum expected salary",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="professionalqualifications",
            name="min_salary",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum expected salary",
                max_digits=10,
                null=True,
            ),
        ),
    ]
