# Generated by Django 5.2 on 2025-06-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0011_professionalqualifications_max_salary_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChoiceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_type", models.CharField(max_length=50, unique=True)),
                ("choices", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Choice Data",
                "verbose_name_plural": "Choice Data",
            },
        ),
    ]
