# Generated by Django 5.2.1 on 2025-06-15 00:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0011_remove_professional_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identityverification",
            name="id_back",
            field=models.ImageField(
                blank=True,
                help_text="Back photo of ID document (optional)",
                null=True,
                upload_to="id_backs/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="identityverification",
            name="id_front",
            field=models.ImageField(
                blank=True,
                help_text="Front photo of ID document (optional)",
                null=True,
                upload_to="id_fronts/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif"]
                    )
                ],
            ),
        ),
    ]
