# Generated by Django 5.2.1 on 2025-06-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0012_make_id_photos_optional"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="name",
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="phone_number",
            field=models.CharField(
                default="+2510000000000",
                help_text="Phone number (auto-populated from registration)",
                max_length=20,
            ),
        ),
    ]
