# Generated by Django 5.2.1 on 2025-06-22 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0013_create_basic_information_bundle"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "housing_status",
                    models.CharField(
                        choices=[
                            ("owned", "Owned"),
                            ("rented", "Rented"),
                            ("living_with_family", "Living with Family"),
                            ("other", "Other"),
                        ],
                        help_text="Housing status (required)",
                        max_length=50,
                    ),
                ),
                (
                    "region",
                    models.CharField(help_text="Region (required)", max_length=100),
                ),
                (
                    "duration",
                    models.CharField(
                        choices=[
                            ("less_than_1_year", "Less than 1 year"),
                            ("1_to_3_years", "1 to 3 years"),
                            ("3_to_5_years", "3 to 5 years"),
                            ("more_than_5_years", "More than 5 years"),
                        ],
                        help_text="Duration of residence (required)",
                        max_length=50,
                    ),
                ),
                ("city", models.CharField(help_text="City (required)", max_length=100)),
                (
                    "country",
                    models.CharField(help_text="Country code (required)", max_length=2),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Full address (required)", max_length=255
                    ),
                ),
                (
                    "specific_area",
                    models.CharField(
                        help_text="Specific area or neighborhood (required)",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_information",
                        to="userprofile.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location Information",
                "verbose_name_plural": "Location Information",
            },
        ),
    ]
