# Generated by Django 5.2.1 on 2025-06-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0013_remove_profile_name_add_contact_phone"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ActorCategoryChoices",
        ),
        migrations.DeleteModel(
            name="AvailabilityChoices",
        ),
        migrations.DeleteModel(
            name="Choices",
        ),
        migrations.DeleteModel(
            name="DurationChoices",
        ),
        migrations.DeleteModel(
            name="EmploymentStatusChoices",
        ),
        migrations.DeleteModel(
            name="ExperienceLevelChoices",
        ),
        migrations.DeleteModel(
            name="GenderChoices",
        ),
        migrations.DeleteModel(
            name="HousingStatusChoices",
        ),
        migrations.DeleteModel(
            name="IDTypeChoices",
        ),
        migrations.DeleteModel(
            name="MaritalStatusChoices",
        ),
        migrations.DeleteModel(
            name="NationalityChoices",
        ),
        migrations.DeleteModel(
            name="ShiftChoices",
        ),
        migrations.DeleteModel(
            name="SkillsChoices",
        ),
        migrations.DeleteModel(
            name="WorkLocationChoices",
        ),
        migrations.DeleteModel(
            name="YearsChoices",
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="housing_status",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="residence_duration",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="gender",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="id_type",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="marital_status",
            field=models.CharField(max_length=20),
        ),
    ]
