# Generated by Django 5.2.1 on 2025-06-22 12:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0014_create_location_information_bundle"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        help_text="Experience level (required)", max_length=50
                    ),
                ),
                (
                    "years",
                    models.CharField(
                        help_text="Years of experience (required)", max_length=50
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        help_text="Availability (required)", max_length=50
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        help_text="Employment status (required)", max_length=50
                    ),
                ),
                (
                    "work_location",
                    models.CharField(
                        help_text="Preferred work location (required)", max_length=50
                    ),
                ),
                (
                    "shift",
                    models.CharField(
                        help_text="Shift preference (required)", max_length=50
                    ),
                ),
                (
                    "skill_videos_url",
                    models.URLField(
                        blank=True, help_text="URL to skill demonstration videos"
                    ),
                ),
                (
                    "experience_description",
                    models.TextField(
                        blank=True, help_text="Detailed description of experience"
                    ),
                ),
                (
                    "industry_experience",
                    models.TextField(
                        blank=True, help_text="Industry-specific experience"
                    ),
                ),
                (
                    "previous_employers",
                    models.JSONField(
                        default=list, help_text="List of previous employers"
                    ),
                ),
                (
                    "portfolio_url",
                    models.URLField(blank=True, help_text="Portfolio URL"),
                ),
                (
                    "training_workshops",
                    models.JSONField(
                        default=list, help_text="Training and workshops attended"
                    ),
                ),
                (
                    "union_membership",
                    models.BooleanField(
                        default=False, help_text="Union membership status"
                    ),
                ),
                (
                    "certifications",
                    models.JSONField(
                        default=list,
                        help_text="Professional certifications (user can add multiple)",
                    ),
                ),
                (
                    "min_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum expected salary",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "max_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum expected salary",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "video_links",
                    models.JSONField(default=list, help_text="Additional video links"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experience",
                        to="userprofile.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Experience",
                "verbose_name_plural": "Experience",
            },
        ),
        migrations.CreateModel(
            name="IDVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_type",
                    models.CharField(
                        help_text="Type of identification document (required)",
                        max_length=50,
                    ),
                ),
                (
                    "front_photo",
                    models.ImageField(
                        blank=True,
                        help_text="Front photo of ID document (required)",
                        null=True,
                        upload_to="id_fronts/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "gif"]
                            )
                        ],
                    ),
                ),
                (
                    "back_photo",
                    models.ImageField(
                        blank=True,
                        help_text="Back photo of ID document (required)",
                        null=True,
                        upload_to="id_backs/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "gif"]
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_verification",
                        to="userprofile.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "ID Verification",
                "verbose_name_plural": "ID Verification",
            },
        ),
        migrations.CreateModel(
            name="ProfessionsAndSkills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor_category",
                    models.CharField(
                        blank=True,
                        help_text="Category of acting experience",
                        max_length=50,
                    ),
                ),
                (
                    "model_categories",
                    models.JSONField(
                        default=list, help_text="Selected model categories"
                    ),
                ),
                (
                    "performer_categories",
                    models.JSONField(
                        default=list, help_text="Selected performer categories"
                    ),
                ),
                (
                    "influencer_categories",
                    models.JSONField(
                        default=list, help_text="Selected influencer categories"
                    ),
                ),
                ("skills", models.JSONField(default=list, help_text="Selected skills")),
                (
                    "main_skill",
                    models.CharField(
                        blank=True,
                        help_text="Primary skill (required for some professions)",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professions_and_skills",
                        to="userprofile.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Professions & Skills",
                "verbose_name_plural": "Professions & Skills",
            },
        ),
    ]
