# Generated by Django 5.2.1 on 2025-06-26 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "userprofile",
            "0015_alter_contactinfo_options_alter_medicalinfo_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactinfo",
            name="address",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="city",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="country",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="housing_status",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="region",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="residence_duration",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="specific_area",
        ),
        migrations.CreateModel(
            name="LocationInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "housing_status",
                    models.CharField(help_text="Housing status", max_length=50),
                ),
                ("region", models.CharField(help_text="Region", max_length=100)),
                (
                    "duration",
                    models.CharField(help_text="Duration of residence", max_length=50),
                ),
                ("city", models.CharField(help_text="City", max_length=100)),
                ("country", models.CharField(help_text="Country code", max_length=2)),
                ("address", models.CharField(help_text="Full address", max_length=255)),
                (
                    "specific_area",
                    models.CharField(
                        help_text="Specific area within the city", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_information",
                        to="userprofile.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location Information",
                "verbose_name_plural": "Location Information",
            },
        ),
    ]
