# Generated by Django 5.2.1 on 2025-06-27 07:13

import django.utils.timezone
import userprofile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "userprofile",
            "0016_remove_contactinfo_address_remove_contactinfo_city_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="education",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="identityverification",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="identityverification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="locationdata",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="locationdata",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workexperience",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="basicinformation",
            name="body_type",
            field=userprofile.models.CaseInsensitiveCharField(
                help_text="Body type", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="basicinformation",
            name="custom_hobby",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True, help_text="Custom hobby", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="basicinformation",
            name="emergency_contact_name",
            field=userprofile.models.CaseInsensitiveCharField(
                help_text="Emergency contact name", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="basicinformation",
            name="eye_color",
            field=userprofile.models.CaseInsensitiveCharField(
                help_text="Eye color", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="basicinformation",
            name="gender",
            field=userprofile.models.CaseInsensitiveCharField(
                help_text="Gender", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="basicinformation",
            name="hair_color",
            field=userprofile.models.CaseInsensitiveCharField(
                help_text="Hair color", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="basicinformation",
            name="marital_status",
            field=userprofile.models.CaseInsensitiveCharField(
                help_text="Marital status", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="basicinformation",
            name="nationality",
            field=userprofile.models.CaseInsensitiveCharField(
                help_text="Nationality", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="basicinformation",
            name="skin_tone",
            field=userprofile.models.CaseInsensitiveCharField(
                help_text="Skin tone", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="basicinformation",
            name="willing_to_travel",
            field=userprofile.models.CaseInsensitiveCharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                help_text="Willingness to travel",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="degree_type",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True, max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="education_level",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True, max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="field_of_study",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True, max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="institution_name",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True, max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="identityverification",
            name="id_type",
            field=userprofile.models.CaseInsensitiveCharField(
                help_text="Type of identification document", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="locationdata",
            name="region_id",
            field=userprofile.models.CaseInsensitiveCharField(
                max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="locationdata",
            name="region_name",
            field=userprofile.models.CaseInsensitiveCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="locationinformation",
            name="address",
            field=userprofile.models.CaseInsensitiveCharField(
                help_text="Full address", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="locationinformation",
            name="city",
            field=userprofile.models.CaseInsensitiveCharField(
                help_text="City", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="locationinformation",
            name="duration",
            field=userprofile.models.CaseInsensitiveCharField(
                help_text="Duration of residence", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="locationinformation",
            name="housing_status",
            field=userprofile.models.CaseInsensitiveCharField(
                help_text="Housing status", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="locationinformation",
            name="region",
            field=userprofile.models.CaseInsensitiveCharField(
                help_text="Region", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="locationinformation",
            name="specific_area",
            field=userprofile.models.CaseInsensitiveCharField(
                help_text="Specific area within the city", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="medicalinfo",
            name="disability_status",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True, max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="medicalinfo",
            name="disability_type",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True, default="None", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="custom_language",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="custom_social_media",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="first_name",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="id_type",
            field=userprofile.models.CaseInsensitiveCharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="last_name",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="physicalattributes",
            name="facial_hair",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True, max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="physicalattributes",
            name="physical_condition",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True, max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="actor_category",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True, help_text="Category of acting experience", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="availability",
            field=userprofile.models.CaseInsensitiveCharField(
                help_text="Availability (required)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="communication_style",
            field=userprofile.models.CaseInsensitiveCharField(
                help_text="Communication style", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="employment_status",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True,
                help_text="Employment status (required)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="experience_level",
            field=userprofile.models.CaseInsensitiveCharField(
                help_text="Experience level (required)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="leadership_style",
            field=userprofile.models.CaseInsensitiveCharField(
                help_text="Leadership style", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="main_skill",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True,
                help_text="Primary skill (required for stuntman)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="motivation",
            field=userprofile.models.CaseInsensitiveCharField(
                help_text="Motivation", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="preferred_company_size",
            field=userprofile.models.CaseInsensitiveCharField(
                help_text="Preferred company size", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="preferred_industry",
            field=userprofile.models.CaseInsensitiveCharField(
                help_text="Preferred industry", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="preferred_work_location",
            field=userprofile.models.CaseInsensitiveCharField(
                help_text="Preferred work location (required)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="role_title",
            field=userprofile.models.CaseInsensitiveCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="shift_preference",
            field=userprofile.models.CaseInsensitiveCharField(
                help_text="Shift preference (required)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="work_authorization",
            field=userprofile.models.CaseInsensitiveCharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="professionalqualifications",
            name="years_of_experience",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True,
                help_text="Years of experience (required)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True, max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profession",
            field=userprofile.models.CaseInsensitiveCharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="status",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True, max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="verificationauditlog",
            name="verification_method",
            field=userprofile.models.CaseInsensitiveCharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="verificationauditlog",
            name="verification_type",
            field=userprofile.models.CaseInsensitiveCharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="verificationstatus",
            name="verification_method",
            field=userprofile.models.CaseInsensitiveCharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="verificationstatus",
            name="verification_type",
            field=userprofile.models.CaseInsensitiveCharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="employment_status",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True, max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="years_of_experience",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True, max_length=50
            ),
        ),
    ]
