# Generated by Django 5.2.1 on 2025-06-27 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0018_actorcategory_influencercategory_mainskill_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactinfo",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="education",
            name="profile",
        ),
        migrations.DeleteModel(
            name="LocationData",
        ),
        migrations.RemoveField(
            model_name="media",
            name="profile",
        ),
        migrations.DeleteModel(
            name="ContactInfo",
        ),
        migrations.DeleteModel(
            name="Education",
        ),
        migrations.DeleteModel(
            name="Media",
        ),
    ]
