# Generated by Django 5.2.1 on 2025-06-28 15:25

import django.core.validators
import userprofile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0019_remove_education_contactinfo_locationdata_media_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicinformation",
            name="body_type",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True, help_text="Body type", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="basicinformation",
            name="date_of_birth",
            field=models.DateField(blank=True, help_text="Date of birth", null=True),
        ),
        migrations.AlterField(
            model_name="basicinformation",
            name="emergency_contact_name",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True,
                help_text="Emergency contact name",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="basicinformation",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True,
                help_text="Emergency contact phone (must start with +251)",
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must start with +251 followed by 9 digits",
                        regex="^\\+251\\d{9}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="basicinformation",
            name="eye_color",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True, help_text="Eye color", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="basicinformation",
            name="gender",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True, help_text="Gender", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="basicinformation",
            name="hair_color",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True, help_text="Hair color", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="basicinformation",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Height in centimeters",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        100, message="Height must be at least 100 cm"
                    ),
                    django.core.validators.MaxValueValidator(
                        300, message="Height cannot exceed 300 cm"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="basicinformation",
            name="hobbies",
            field=models.JSONField(
                blank=True, default=list, help_text="Hobbies", null=True
            ),
        ),
        migrations.AlterField(
            model_name="basicinformation",
            name="languages",
            field=models.JSONField(
                blank=True, default=list, help_text="Languages spoken", null=True
            ),
        ),
        migrations.AlterField(
            model_name="basicinformation",
            name="marital_status",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True, help_text="Marital status", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="basicinformation",
            name="medical_condition",
            field=models.JSONField(
                blank=True, default=list, help_text="Medical conditions", null=True
            ),
        ),
        migrations.AlterField(
            model_name="basicinformation",
            name="medicine_type",
            field=models.JSONField(
                blank=True, default=list, help_text="Types of medicine", null=True
            ),
        ),
        migrations.AlterField(
            model_name="basicinformation",
            name="nationality",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True, help_text="Nationality", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="basicinformation",
            name="skin_tone",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True, help_text="Skin tone", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="basicinformation",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Weight in kilograms",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        30, message="Weight must be at least 30 kg"
                    ),
                    django.core.validators.MaxValueValidator(
                        500, message="Weight cannot exceed 500 kg"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="basicinformation",
            name="willing_to_travel",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                help_text="Willingness to travel",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="portfolio_url",
            field=models.URLField(blank=True, help_text="Portfolio URL"),
        ),
        migrations.AlterField(
            model_name="experience",
            name="video_links",
            field=models.JSONField(
                blank=True, default=list, help_text="List of video links"
            ),
        ),
        migrations.AlterField(
            model_name="headshot",
            name="professional_headshot",
            field=models.ImageField(
                blank=True,
                help_text="Professional headshot. Must be JPG/PNG/JPEG format, minimum 800px width, maximum 2000px width.",
                null=True,
                upload_to="headshots/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                    django.core.validators.MinValueValidator(
                        800, message="Image width must be at least 800 pixels"
                    ),
                    django.core.validators.MaxValueValidator(
                        2000, message="Image width must not exceed 2000 pixels"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="identityverification",
            name="id_back",
            field=models.ImageField(
                blank=True,
                help_text="Back photo of ID document",
                null=True,
                upload_to="id_backs/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="identityverification",
            name="id_front",
            field=models.ImageField(
                blank=True,
                help_text="Front photo of ID document",
                null=True,
                upload_to="id_fronts/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="identityverification",
            name="id_type",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True,
                help_text="Type of identification document (National ID, Passport, Driving License)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="locationinformation",
            name="address",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True, help_text="Full address", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="locationinformation",
            name="city",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True, help_text="City", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="locationinformation",
            name="country",
            field=models.CharField(
                blank=True, help_text="Country code", max_length=2, null=True
            ),
        ),
        migrations.AlterField(
            model_name="locationinformation",
            name="duration",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True, help_text="Duration of residence", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="locationinformation",
            name="housing_status",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True, help_text="Housing status", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="locationinformation",
            name="region",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True, help_text="Region", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="locationinformation",
            name="specific_area",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True,
                help_text="Specific area within the city",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="naturalphotos",
            name="natural_photo_1",
            field=models.ImageField(
                blank=True,
                help_text="First natural photo. Must be JPG/PNG/JPEG format, minimum 800px width, maximum 2000px width.",
                null=True,
                upload_to="natural_photos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                    django.core.validators.MinValueValidator(
                        800, message="Image width must be at least 800 pixels"
                    ),
                    django.core.validators.MaxValueValidator(
                        2000, message="Image width must not exceed 2000 pixels"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="naturalphotos",
            name="natural_photo_2",
            field=models.ImageField(
                blank=True,
                help_text="Second natural photo. Must be JPG/PNG/JPEG format, minimum 800px width, maximum 2000px width.",
                null=True,
                upload_to="natural_photos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                    django.core.validators.MinValueValidator(
                        800, message="Image width must be at least 800 pixels"
                    ),
                    django.core.validators.MaxValueValidator(
                        2000, message="Image width must not exceed 2000 pixels"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="language_proficiency",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="professionsandskills",
            name="professions",
            field=models.JSONField(default=list, help_text="Selected professions"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="birthdate",
            field=models.DateField(blank=True, help_text="Date of birth", null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profession",
            field=userprofile.models.CaseInsensitiveCharField(
                blank=True, max_length=50, null=True
            ),
        ),
        migrations.DeleteModel(
            name="PhysicalAttributes",
        ),
    ]
