# Generated by Django 5.2.1 on 2025-06-28 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0020_remove_physical_attributes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MedicalInfo",
        ),
    ]
