# Generated by Django 5.2.1 on 2025-06-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0021_remove_medical_info"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PersonalInfo",
        ),
    ]
