# Generated by Django 5.2.1 on 2025-06-29 21:30

import userprofile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0023_remove_profile_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicinformation",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                help_text="Date of birth (must be between 18-100 years old)",
                null=True,
                validators=[userprofile.models.validate_date_of_birth],
            ),
        ),
    ]
