# Generated by Django 5.2.1 on 2025-07-01 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0023_remove_profile_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="headshot",
            name="professional_headshot",
            field=models.ImageField(
                blank=True,
                help_text="Professional headshot. Must be JPG/PNG/JPEG format, minimum 800px width, maximum 2000px width.",
                null=True,
                upload_to="media/headshots/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                    django.core.validators.MinValueValidator(
                        800, message="Image width must be at least 800 pixels"
                    ),
                    django.core.validators.MaxValueValidator(
                        2000, message="Image width must not exceed 2000 pixels"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="identityverification",
            name="id_back",
            field=models.ImageField(
                blank=True,
                help_text="Back photo of ID document",
                null=True,
                upload_to="media/id_backs/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="identityverification",
            name="id_front",
            field=models.ImageField(
                blank=True,
                help_text="Front photo of ID document",
                null=True,
                upload_to="media/id_fronts/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="naturalphotos",
            name="natural_photo_1",
            field=models.ImageField(
                blank=True,
                help_text="First natural photo. Must be JPG/PNG/JPEG format, minimum 800px width, maximum 2000px width.",
                null=True,
                upload_to="media/natural_photos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                    django.core.validators.MinValueValidator(
                        800, message="Image width must be at least 800 pixels"
                    ),
                    django.core.validators.MaxValueValidator(
                        2000, message="Image width must not exceed 2000 pixels"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="naturalphotos",
            name="natural_photo_2",
            field=models.ImageField(
                blank=True,
                help_text="Second natural photo. Must be JPG/PNG/JPEG format, minimum 800px width, maximum 2000px width.",
                null=True,
                upload_to="media/natural_photos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                    django.core.validators.MinValueValidator(
                        800, message="Image width must be at least 800 pixels"
                    ),
                    django.core.validators.MaxValueValidator(
                        2000, message="Image width must not exceed 2000 pixels"
                    ),
                ],
            ),
        ),
    ]
