# Generated by Django 5.2.1 on 2025-07-02 07:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0024_alter_basicinformation_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="headshot",
            name="professional_headshot",
            field=models.ImageField(
                blank=True,
                help_text="Professional headshot. Must be JPG/PNG/JPEG format.",
                null=True,
                upload_to="headshots/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="naturalphotos",
            name="natural_photo_1",
            field=models.ImageField(
                blank=True,
                help_text="First natural photo. Must be JPG/PNG/JPEG format.",
                null=True,
                upload_to="natural_photos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="naturalphotos",
            name="natural_photo_2",
            field=models.ImageField(
                blank=True,
                help_text="Second natural photo. Must be JPG/PNG/JPEG format.",
                null=True,
                upload_to="natural_photos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
