# Generated by Django 5.2 on 2025-07-03 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0026_alter_headshot_professional_headshot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="headshot",
            name="professional_headshot",
            field=models.ImageField(
                blank=True,
                help_text="Professional headshot. Must be JPG/PNG/JPEG format.",
                null=True,
                upload_to="media/headshots/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="naturalphotos",
            name="natural_photo_1",
            field=models.ImageField(
                blank=True,
                help_text="First natural photo. Must be JPG/PNG/JPEG format.",
                null=True,
                upload_to="media/natural_photos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="naturalphotos",
            name="natural_photo_2",
            field=models.ImageField(
                blank=True,
                help_text="Second natural photo. Must be JPG/PNG/JPEG format.",
                null=True,
                upload_to="media/natural_photos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
