# Generated by Django 5.2 on 2025-07-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_ratings", "0001_initial"),
        ("userprofile", "0027_alter_headshot_professional_headshot_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userrating",
            name="unique_user_rating",
        ),
        migrations.RemoveField(
            model_name="userrating",
            name="rated_user_id",
        ),
        migrations.RemoveField(
            model_name="userrating",
            name="rating_user_id",
        ),
        migrations.AddConstraint(
            model_name="userrating",
            constraint=models.UniqueConstraint(
                fields=("rater_profile_id", "rated_profile_id"),
                name="unique_user_rating",
            ),
        ),
    ]
