# Generated by Django 5.2 on 2025-05-08 11:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the advert",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.URLField(
                        blank=True, help_text="URL to the advert's image", null=True
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the advert", max_length=200),
                ),
                (
                    "video",
                    models.URLField(
                        blank=True, help_text="URL to the advert's video", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the advert was created",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the advert",
                        null=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the advert was last updated",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        help_text="Current status of the advert (e.g., Draft, Published)",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Location or region for the advert",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "run_from",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start date and time for the advert campaign",
                        null=True,
                    ),
                ),
                (
                    "run_to",
                    models.DateTimeField(
                        blank=True,
                        help_text="End date and time for the advert campaign",
                        null=True,
                    ),
                ),
            ],
        ),
    ]
