# Generated by Django 5.2.1 on 2025-06-02 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("adverts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="advert",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created the advert",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adverts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
