# Generated by Django 5.2 on 2025-05-01 08:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='created_by',
            field=models.ForeignKey(help_text='User who created the advert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adverts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advert',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the advert', null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='location',
            field=models.CharField(blank=True, help_text='Location or region for the advert', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='run_from',
            field=models.DateTimeField(blank=True, help_text='Start date and time for the advert campaign', null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='run_to',
            field=models.DateTimeField(blank=True, help_text='End date and time for the advert campaign', null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived'), ('expired', 'Expired')], default='draft', help_text='Current status of the advert (e.g., Draft, Published)', max_length=20),
        ),
        migrations.AddField(
            model_name='advert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the advert was last updated'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the advert was created'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the advert', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='advert',
            name='image',
            field=models.URLField(blank=True, help_text="URL to the advert's image", null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='title',
            field=models.CharField(help_text='Title of the advert', max_length=200),
        ),
        migrations.AlterField(
            model_name='advert',
            name='video',
            field=models.URLField(blank=True, help_text="URL to the advert's video", null=True),
        ),
    ]
