# Generated by Django 5.2 on 2025-05-15 23:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("feed_comments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentReaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_dislike", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        db_column="comment_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="feed_comments.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "comment_reactions",
                "indexes": [
                    models.Index(
                        fields=["comment", "user"],
                        name="comment_rea_comment_b16750_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="comment_rea_user_id_f54a31_idx",
                    ),
                    models.Index(
                        fields=["comment", "is_dislike"],
                        name="comment_rea_comment_d3fef9_idx",
                    ),
                ],
                "unique_together": {("comment", "user")},
            },
        ),
    ]
