# Generated by Django 5.2 on 2025-05-13 20:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("feed_posts", "0002_remove_feedpost_media_urls_alter_feedpost_media_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the like",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the post was liked"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        help_text="The post that was liked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="feed_posts.feedpost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who liked the post",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("post", "user")},
            },
        ),
    ]
