# Generated by Django 5.2.1 on 2025-07-04 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed_likes", "0001_initial"),
        ("userprofile", "0027_alter_headshot_professional_headshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedlike",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                help_text="Profile who liked the post",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_likes",
                to="userprofile.profile",
            ),
        ),
    ]
